server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

# Environment variables mapping
groq:
  api-key: ${GROQ_API_KEY:}

pinecone:
  api-key: ${PINECONE_API_KEY:}
  host: ${PINECONE_HOST:}

# THE FIX: Bridge the HF Key
huggingface:
  api-key: ${HF_API_KEY:}

admin:
  api-key: ${ADMIN_API_KEY}

cors:
  allowed-origin: ${FRONTEND_ORIGIN:http://localhost:3000}